apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-external-access
  namespace: ken-y-j-tansp
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 128.161.251.11/32
    - ipBlock:
        cidr: 192.168.216.10/32        
