apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-squid
spec:
  hosts:
  - squid.egress.svc.cluster.local
  ports:
  - name: http
    number: 3128
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-squid
spec:
  hosts:
  - squid.egress.svc.cluster.local
  tls:
  - match:
    - port: 443
      sni_hosts:
      - squid.egress.svc.cluster.local
    route:
    - destination:
        host: squid.egress.svc.cluster.local
        port:
          name: http
