apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-outbound-traffic
spec:
  podSelector:
    matchLabels:
      app: my-app
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          environment: prod
    ports:
    - protocol: TCP
      port: 80
